### PR TITLE
Implement UI for TrackO

### LINKED ISSUE #74: Update application window name
Currently, the application starts up as "Address App". This issue is to change it to "TrackO" instead.

### LINKED ISSUE #83: Implement JavaFX GUI

### PR DESCRIPTION
**Pull request by melissaharijanto**
When the app is first opened, it should look something like this (with more than just placeholder data):  
Screen Shot 2022-10-13 at 04 35 14

The title `AddressBook` has also been changed to `TrackO`, what we can probably do more is to change the logo.

Design changes from initial prototype
- Description has a container, to make it less confusing as quantity doesn't have an icon for itself
- Headers for `inventory` and `orders` are located outside of the `ListVIew`, unlike the prototype where it's inside. This is because the `ListView` functions much like a FlatList and it is difficult to add in only one component to the cell with a completely different style compared to the others.

I tested a few inputs:
- one with long name (tested with the world's longest name to see if the text wraps, and it does although it makes the UI look kind of tacky):

https://user-images.githubusercontent.com/97304787/195481629-57350c86-aa06-478b-b69f-c050c30af68e.mov

- one with multiple items for orders:
Screen Shot 2022-10-13 at 04 36 48

- inventory item with a very long name and a very long description

https://user-images.githubusercontent.com/97304787/195481770-b0fa6ad2-f853-43f9-b0bf-608008290d29.mov

These should be good to merge for now.

**One minor issue** I am finding ways to fix is the result display in the screenshot below.
Screen Shot 2022-10-13 at 04 34 40

**One nice thing to have:** I am trying to make the item quantity stand out from the rest of the text, but still unsure on how to do it. Feel free to tell me any suggestions that you have!

The result display looks cut off, though it's actually scrollable and the whole data shows. I am finding ways to keep the container consistent, and just the text to be scrollable.

This is how it looks like with only the placeholder data. Perhaps we can add placeholder inventory items to the JSON too?
Screen Shot 2022-10-13 at 10 08 47

Let me know what you think!

### CODE REVIEW

**Comment by melissaharijanto** [comment]
**Update on the minor issue** result display works well now! 

https://user-images.githubusercontent.com/97304787/195490238-ec1e6397-a26f-4baa-adb4-d66d2ff762fb.mov

**Review by janelleljt — APPROVED** [review]

**Comment by melissaharijanto** [comment]
Screen Shot 2022-10-13 at 11 52 26

Footer font color changed: `./data/trackO.json` now shows at the bottom left corner!

**Comment by melissaharijanto** [comment]
Screen Shot 2022-10-13 at 14 34 25

Colors are modified to match the prototype more!

**Comment by melissaharijanto** [comment]
Screen Shot 2022-10-13 at 17 40 07

Tried making the `Quantity` of an `InventoryItem` stand out more!
Removed the description box so it doesn't take attention away from the `Quantity` box.

**Comment by donljh** [comment]
This looks really good. Awesome work!

**Review by donljh — APPROVED** [review]
Great work, appreciate it! Looks very professional and well done

**Pull request merged**
