### PR TITLE
Update User Guide with features: tagi and exit

### LINKED ISSUE #23: Update User Guide (Enze)

### PR DESCRIPTION
**Pull request by sohenze**

### CODE REVIEW

**Comment by sohenze** [comment]
I removed the other commands under the Features and Command Summary sections but should I remove the other sections as well? (Introduction, Quick Start, FAQ)

**Comment by sohenze** [comment]
I followed Janelle and have removed all the other sections

**Review by melissaharijanto — APPROVED** [review]
I think this looks good already!

**Review by Jiacheng-y — APPROVED** [review]
Looks good!

**Pull request merged**
